inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

Exclude:
    - 'vendor/**/*'
    - 'bin/**/*'
    - 'db/**/*'
    - 'config/**/*'
    - 'tmp/**/*'
    - 'node_modules/**/*'
    - 'lib/tasks/auto_annotate_models.rake'

# 日本語のコメントを許可
Style/AsciiComments:
  Enabled: false